### ISSUE TITLE
Warning: The X rule requires type information

### ISSUE THREAD

**Issue by unlight** [JamesHenry/eslint-plugin-tslint#32]
```
Warning: The 'no-use-before-declare' rule requires type information.
Warning: The 'await-promise' rule requires type information.
Warning: The 'match-default-export-name' rule requires type information.
Warning: The 'no-floating-promises' rule requires type information.
Warning: The 'no-for-in-array' rule requires type information.
Warning: The 'no-unsafe-any' rule requires type information.
Warning: The 'promise-function-async' rule requires type information.
Warning: The 'restrict-plus-operands' rule requires type information.
Warning: The 'strict-boolean-expressions' rule requires type information.
Warning: The 'completed-docs' rule requires type information.
Warning: The 'no-unnecessary-qualifier' rule requires type information.
Warning: The 'no-void-expression' rule requires type information.
```

For such rules `ts.Program` instance is required
https://palantir.github.io/tslint/usage/type-checking/

Can you add support?

**Comment by unlight** [comment]
#33

**Comment by ShadabFaiz** [comment]
So, for using the above mentioned rules, i have to install eslint-plugin-tslint
 and configure my project ot use eslint instead of tslint? Is there any other way?

**Comment by unlight** [comment]
You have to install eslint-plugin-tslint@^3 (v3+).

> configure my project ot use eslint instead

And you have to install typescript-eslint-parser which allows to eslint to parse typescript syntax.
See example of [.eslintrc.js](https://github.com/unlight/node-package-starter/blob/master/.eslintrc.js)
