### ISSUE TITLE
No output.

### ISSUE THREAD

**Issue by trusktr** [JamesHenry/eslint-plugin-tslint#35]
I'm on the latest everything.

There only JS-specific output, but nothing about tslint rules. If I remove the tslint plugin, it's the same output, as if tslint plugin isn't doing anything.

Probably needs an update for the latest eslint and/or typescript parser.

**Comment by unlight** [comment]
@trusktr 
I suspect that you did not configure rules.
Please, check latest readme of version (3.0.0)
https://github.com/JamesHenry/eslint-plugin-tslint
