### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ackvf** [JamesHenry/eslint-plugin-tslint#36]
It would be great if there was more information about how this works (how is it similar or different from eslint-plugin-typescript) and an installation documentation somewhere.

**Comment by unlight** [comment]
I will try to answer.

`eslint-plugin-typescript` is a parser, transform typescript source code to syntax tree which can be consumed properly by ESLint/plugins.

1. `eslint-plugin-tslint` is the plugin for ESLint allow to apply some TSLint rules for typescript and (in theory) for JavaScript files.
But there are some restrictions:
* No rules wich requires type information #33 
* No tsx support #34 
2. Under the hood `eslint-plugin-tslint` uses tslint and it's API.
3. `eslint-plugin-tslint` contains only single rule `tslint/config`
4. How to configure:
* add to `plugins` section:
```
tslint
```
* to `rules` section add:
```
'tslint/config': [1, {
   rules: tslintConfigRules,
   rulesDirectory: tslintConfigRulesDirectory,
}]
```
where:
`tslintConfigRules` same as rules in tslint.json
Example:
```
{
    'interface-over-type-literal': true,
    'ban-types': true,
}
```
`tslintConfigRulesDirectory` array of paths to directories with rules,
Example:
```
[
    'node_modules/tslint/lib/rules',
]
```
[See example](https://github.com/unlight/node-package-starter/blob/master/.eslintrc.js)

You can try another similar ESLint plugin [eslint-plugin-tsc](https://github.com/unlight/eslint-plugin-tsc) which wraps typescript checks.
