### ISSUE TITLE
eslint-plugin-tslint2

### ISSUE THREAD

**Issue by unlight** [JamesHenry/eslint-plugin-tslint#37]
Forked and published [eslint-plugin-tslint2](https://github.com/unlight/eslint-plugin-tslint2).
The main difference are:
- Support rules which requires type information

/cc @JamesHenry

**Comment by JamesHenry** [comment]
I'm very sorry about not replying to you sooner, @unlight! Would you like to become a collaborator on the original repo/package instead? You can then merge anything you feel is appropriate.

Thanks again

**Comment by unlight** [comment]
@JamesHenry 
Sounds good. I would love to contribute.

**Comment by JamesHenry** [comment]
Invited! Thanks a lot :)

**Comment by unlight** [comment]
@JamesHenry 
Can you check logs https://travis-ci.org/JamesHenry/eslint-plugin-tslint/jobs/425215834 ?
Error says that `NPM_TOKEN` is not valid.

**Comment by JamesHenry** [comment]
@unlight I have updated it and rerun the build. A new version was published successfully. Thanks!
